name: Simple Maven app
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java & maven
      uses: evryfs/composite-java-action@v0.4.6
      with:
        java-version: '11'
        maven-version: '3.8.1'
        cache: true
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install --file pom.xml    
